name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -scheme coo-questionary -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11"
    - name: Run tests
      run: xcodebuild test  -scheme coo-questionary -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11"
